*** Variables ***
${PRACTICE_FORM_INPUT_FIRST_NAME}        xpath=//input[@id='firstName']
${PRACTICE_FORM_INPUT_LAST_NAME}         xpath=//input[@id='lastName']
${PRACTICE_FORM_INPUT_EMAIL}             xpath=//input[@id='userEmail']
${PRACTICE_FORM_RADIO_MALE}              xpath=//label[@for='gender-radio-1']
${PRACTICE_FORM_RADIO_FEMALE}            xpath=//label[@for='gender-radio-2']
${PRACTICE_FORM_INPUT_MOBILE_NUMBER}     xpath=//input[@id='userNumber']
${PRACTICE_FORM_INPUT_DATE_OF_BIRTH}     xpath=//input[@id='dateOfBirthInput']
${PRACTICE_FORM_INPUT_SUBJECTS}          xpath=//input[@id='subjectsInput']
${PRACTICE_FORM_CHECKBOX_SPORTS}         xpath=//label[@for='hobbies-checkbox-1']
${PRACTICE_FORM_INPUT_UPLOAD_PICTURE}    xpath=//input[@id='uploadPicture']
${PRACTICE_FORM_TEXT_AREA_ADDRESS}       xpath=//textarea[@id='currentAddress']
${PRACTICE_FORM_BUTTON_SUBMIT}           xpath=//button[@id='submit']
${PRACTICE_FORM_MODAL_TITLE}             xpath=//div[@id='example-modal-sizes-title-lg']
${PRACTICE_FORM_BUTTON_CLOSE_MODAL}      xpath=//button[@id='closeLargeModal']